# Step 1: Build the application
FROM gradle:8.5-jdk21 AS builder
WORKDIR /app
COPY . .
RUN gradle clean build -x test && ls -R /app/build/libs

# Step 2: Run the application
FROM eclipse-temurin:21-jdk
WORKDIR /app

# Copy only the JAR from the build stage
COPY --from=builder /app/build/libs/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-Dserver.port=${PORT}", "-jar", "app.jar"]